# This is a basic workflow to help you get started with Actions

name: Profile Check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run check for READ.ME
        run: |
              if [ ! -f README.md ]; then
              echo "ERROR: README.md not found!"
              exit 1
              fi
              
      - name: Run check for Headings
        run: |
              if ! grep -q '^## Skills ' README.md; then
              echo "ERROR: Skills heading missing!"
              exit 1
              fi
              if ! grep -q '^### Learning and Development ' README.md; then
              echo "ERROR: L&D heading missing!"
              exit 1
              fi
